title: Default Page

columns:
  #main
  main:
    width: 2/3
    sections:

      content:
        type: fields
        fields:
          text:
            label: Text
            type: editor
            size: large

  # sidebar
  sidebar:
    width: 1/3
    sections:

      pages:
        headline: Unterseiten
        create: subpage

      files:
        type: files
        headline: Bilder
        layout: cards





